# R packages -- "bigdatapackages.R"
# for standard install in Bloomberg Lab
install.packages("AppliedPredictiveModeling")
install.packages("arules")
install.packages("arulesViz")
install.packages("caret", dependencies = c("Depends", "Suggests"))
install.packages("corrplot")
install.packages("dplyr")
install.package("e1071")
install.packages("ElemStatLearn")
install.packages("gcookbook")
install.packages("ggmap")
install.packages("ggplot2")
install.packages("ggvis")
install.packages("googleVis")
install.packages("httr")
install.packages("igraph")
install.packages("knitr")
install.packages("lubridate")
install.packages("manipulate")
install.packages("maps")
install.packages("party")
install.packages("plotly")
install.packages("readr")
install.packages("reshape2")
install.packages("rggobi")
install.packages("rpart")
install.packages("shiny")
install.packages("SnowballC")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("tm")

# Especially for BUS256 Marketing Analytics
install.packages("car")
install.packages("ChoiceModelR")
install.packages("gam")
install.packages("igraph")
install.packages("nnet")
install.packages("quantmod")
install.packages("Quandl")
install.packages("randomForest")
install.packages("RColorBrewer")
install.packages("RCurl")
install.packages("ROCR")
install.packages("rpart.plot") 
install.packages("support.CEs")
install.packages("vcd")
install.packages("wordcloud")
install.packages("XML")
install.packages("xts")
install.packages("zoo")
